ALTER TABLE [dbo].[SanPham]
    ADD CONSTRAINT [PK_SanPham] PRIMARY KEY CLUSTERED ([MaHH] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

